set(KIWI_ARCH "x86")
if (CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(KIWI_ARCH "x64")
endif ()

string(TOLOWER ${CMAKE_SYSTEM_NAME} KIWI_SYSTEM_NAME)
if (MSVC)
  string(TOLOWER "msvc${CMAKE_C_COMPILER_VERSION}" KIWI_COMPILER_TARGET)
else ()
  string(TOLOWER "${CMAKE_C_COMPILER_ID}" KIWI_COMPILER_TARGET)
endif (MSVC)

set(CPACK_PACKAGE_VENDOR "Leonardo G. L. de Freitas")
set(CPACK_PACKAGE_DESCRIPTION
  "KiWi - Killer Widgets is a GUI library written in C99 for games and other
   interactive software")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${CMAKE_PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${PROJECT_VERSION}-${KIWI_SYSTEM_NAME}-${KIWI_ARCH}-${KIWI_COMPILER_TARGET}")
set(CPACK_SOURCE_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${PROJECT_VERSION}")

set(CPACK_SOURCE_IGNORE_FILES .*build.*/ .idea/)

if (WIN32)
  set(CPACK_SOURCE_GENERATOR "ZIP")
  set(CPACK_GENERATOR "ZIP")
else()
  set(CPACK_SOURCE_GENERATOR "TGZ")
  set(CPACK_GENERATOR "TGZ")
endif()

include(CPack)